name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to deploy on PR
    # https://docs.github.com/en/actions/managing-workflow-runs/starting-a-workflow-manually#manual-workflow-examples

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build Docusaurus website
        run: yarn build

      # Popular ways to deploy to GitHub Pages
      # See https://docusaurus.io/docs/deployment for more information.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output will be deployed to the `gh-pages` branch
          publish_dir: ./build
          # The following will only be necessary if your Docusaurus project is NOT in the root of your repository
          # For example, if your Docusaurus project is in a subdirectory called "website"
          # publish_branch: gh-pages # Default: gh-pages
          # publish_dir: ./website/build # Default: build
